### ISSUE TITLE
Not compatible with Python < 3.3

### ISSUE THREAD

**Issue by snario** [axltxl/m2bk#7]
Hopefully this isn't too much of a hassle to add compatibility for?

**Comment by ricoveri** [comment]
It wouldn't be if it weren't for a bug in envoy which is keeping m2bk from being compatible with python 3.2:

``` python
Traceback (most recent call last):
  File "/home/axltxl/.pyenv/versions/m2bk3.2/bin/m2bk", line 9, in <module>
    load_entry_point('m2bk===0.3.0-81-g980083d-dirty', 'console_scripts', 'm2bk')()
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/m2bk/app.py", line 19, in <module>
    from m2bk import config, log, mongo, fs
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/m2bk/mongo.py", line 15, in <module>
    from . import log, utils, fs, shell
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/m2bk/shell.py", line 14, in <module>
    import envoy  # envoy is awesome for this job
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/envoy/__init__.py", line 3, in <module>
    from .core import Command, ConnectedCommand, Response
  File "/home/axltxl/.pyenv/versions/m2bk3.2/lib/python3.2/site-packages/envoy/core.py", line 217
    out, err = '', u"\n".join([e.strerror, traceback.format_exc()])
```

Thank you for your contribution :wine_glass: :relaxed:
